Forgot to remove venv testing for allzpark

diff --git a/dotfiles/.local/bin/launchers/allzpark b/dotfiles/.local/bin/launchers/allzpark
--- a/dotfiles/.local/bin/launchers/allzpark
+++ b/dotfiles/.local/bin/launchers/allzpark
@@ -2,11 +2,11 @@
 
 # bash --init-file <(echo "export PS1='[\u@\h \W]\$ '; source $HOME/.local/share/virtualenvs/allzpark-70d0NPiC/bin/activate")
 
-venv=$(cd $HOME/src/rez/rez-venv && pipenv --venv)
-if [[ -z $venv || ! -d $venv ]]; then
-    echo "Could not find virtual env for Allzpark."
-    exit 1
-fi
+# venv=$(cd $HOME/src/rez/rez-venv && pipenv --venv)
+# if [[ -z $venv || ! -d $venv ]]; then
+#     echo "Could not find virtual env for Allzpark."
+#     exit 1
+# fi
 # source $venv/bin/activate
 # ALLZPARK_CONFIG_FILE=$HOME/.config/allzparkrc allzpark
 # xhost + local:
