Make venv detection generic

diff --git a/dotfiles/.local/bin/launchers/allzpark b/dotfiles/.local/bin/launchers/allzpark
--- a/dotfiles/.local/bin/launchers/allzpark
+++ b/dotfiles/.local/bin/launchers/allzpark
@@ -2,5 +2,10 @@
 
 # bash --init-file <(echo "export PS1='[\u@\h \W]\$ '; source $HOME/.local/share/virtualenvs/allzpark-70d0NPiC/bin/activate")
 
-source $HOME/.local/share/virtualenvs/allzpark-70d0NPiC/bin/activate
+venv=$(cd $HOME/src/rez/allzpark && pipenv --venv)
+if [[ -z $venv ]]; then
+    echo "Could not find virtual env for Allzpark."
+    exit 1
+fi
+source $venv/bin/activate
 ALLZPARK_CONFIG_FILE=$HOME/.config/allzparkrc allzpark
diff --git a/dotfiles/.local/bin/launchers/rezvenv b/dotfiles/.local/bin/launchers/rezvenv
--- a/dotfiles/.local/bin/launchers/rezvenv
+++ b/dotfiles/.local/bin/launchers/rezvenv
@@ -7,4 +7,9 @@
 # echo "cd-ing to previous dir"
 # cd $currentdir
 # bash "source $HOME/.local/share/virtualenvs/rez-venv-EJj29fqV/bin/activate"
-bash --init-file <(echo "export PS1='[\u@\h \W]\$ '; source $HOME/.local/share/virtualenvs/rez-venv-EJj29fqV/bin/activate")
+venv=$(cd $HOME/src/rez/rez-venv && pipenv --venv)
+if [[ -z $venv ]]; then
+    echo "Could not find virtual env for (Bleeding) Rez."
+    exit 1
+fi
+bash --init-file <(echo "export PS1='[\u@\h \W]\$ '; source $venv/bin/activate")
