Updates and added pomodoro launcher

diff --git a/dotfiles/.local/bin/launchers/rezblender b/dotfiles/.local/bin/launchers/rezblender
--- a/dotfiles/.local/bin/launchers/rezblender
+++ b/dotfiles/.local/bin/launchers/rezblender
@@ -6,12 +6,13 @@
 #     exit 1
 # fi
 # bash --init-file <(echo "export PS1='[\u@\h \W]\$ '; source $venv/bin/activate; rez-env blender -- blender && exit")
-rezvenvdir=$HOME/src/rez/rez-venv
-if [[ ! -d $rezvenvdir ]]; then
-    message="Could not find the Rez virtualenv to launch the Rez installed version of Blender."
-    notify-send --app-name=rezblender " Failed to start Blender" $message
-    echo "$message ($rezvenvdir)"
-    exit 1
-fi
-cd $rezvenvdir
-$TERMINAL -t blender-show -e pipenv run rez-env blender $@ -- blender
+# rezvenvdir=$HOME/src/rez/rez-venv
+# if [[ ! -d $rezvenvdir ]]; then
+#     message="Could not find the Rez virtualenv to launch the Rez installed version of Blender."
+#     notify-send --app-name=rezblender " Failed to start Blender" $message
+#     echo "$message ($rezvenvdir)"
+#     exit 1
+# fi
+# cd $rezvenvdir
+# $TERMINAL -t blender-show -e pipenv run rez-env blender $@ -- blender
+$TERMINAL -t blender-show -e rez env blender -- blender --python-use-system-env $@
