Update Rez installed Blender launcher

diff --git a/dotfiles/.local/bin/launchers/rezblender b/dotfiles/.local/bin/launchers/rezblender
--- a/dotfiles/.local/bin/launchers/rezblender
+++ b/dotfiles/.local/bin/launchers/rezblender
@@ -1,8 +1,15 @@
 #!/bin/bash
 
-venv=$(cd $HOME/src/rez/rez-venv && pipenv --venv)
-if [[ -z $venv ]]; then
-    echo "Could not find virtual env for (Bleeding) Rez."
+# venv=$(cd $HOME/src/rez/rez-venv && pipenv --venv)
+# if [[ -z $venv ]]; then
+#     echo "Could not find virtual env for (Bleeding) Rez."
+#     exit 1
+# fi
+# bash --init-file <(echo "export PS1='[\u@\h \W]\$ '; source $venv/bin/activate; rez-env blender -- blender && exit")
+rezvenvdir=$HOME/src/rez/rez-venv
+if [[ ! -d $rezvenvdir ]]; then
+    message="Could not find the Rez virtualenv to launch the Rez installed version of Blender."
+    notify-send --app-name=rezblender " Failed to start Blender" $message
+    echo "$message ($rezvenvdir)"
     exit 1
-fi
-bash --init-file <(echo "export PS1='[\u@\h \W]\$ '; source $venv/bin/activate; rez-env blender -- blender && exit")
+cd $rezvenvdir && pipenv run rez-env blender -- blender
